// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApi.Models;

namespace ToDoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200814020512_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoApi.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("PercentComplete")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "nail",
                            Description = "Get requirement details and create estimation",
                            ExpiryDate = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PercentComplete = 0.0,
                            Title = "Analyze requirement"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "nail",
                            Description = "Create new restful api project",
                            ExpiryDate = new DateTime(2020, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PercentComplete = 0.0,
                            Title = "Develop restful API"
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "nail",
                            Description = "Unit test the restful api",
                            ExpiryDate = new DateTime(2020, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PercentComplete = 0.0,
                            Title = "Unit test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
